spring:

  application:
    name: pet-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pet-service
    username: pet_service
    password: pet_service
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # потому что миграции делает Liquibase
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog.yaml

logging:
  level:
    root: INFO
    com.larchflap.pet_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
